name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Build
    #  run: swift build -v
    #- name: Run tests
    #  run: swift test -v
    - name: xcodebuild test
      run: xcodebuild test -scheme SamplePkg2-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest' -verbose
